---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}--config
  labels:
    app: {{ template "nifireg.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $k, $v := .Values.configmapData }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}